version: '3.8'

services:
  # 1. Cơ sở dữ liệu MongoDB
  mongodb:
    image: mongo:6
    container_name: vocab_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

  # backend:
  #   build:
  #     context: ./vocab-battle-backend
  #     dockerfile: Dockerfile
  #   container_name: vocab_backend
  #   ports:
  #     - "8080:8080"
  #   environment:
  #     # Sử dụng tên service "mongodb" thay vì localhost
  #     - MONGO_URI=mongodb://mongodb:27017
  #     - DB_NAME=vocab_battle
  #   depends_on:
  #     - mongodb
  #   restart: unless-stopped

  # frontend:
  #   build:
  #     context: ./vocab-battle-client
  #     dockerfile: Dockerfile
  #     args:
  #       # Đường dẫn tới server WS từ phía client (trình duyệt)
  #       - NEXT_PUBLIC_WS_URL=ws://localhost:8080/ws
  #   container_name: vocab_frontend
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - backend
  #   restart: unless-stopped

volumes:
  mongo_data: