FROM golang:1.25-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN go test ./... && CGO_ENABLED=0 GOOS=linux go build -o main ./cmd/server

FROM alpine:3.22

WORKDIR /app
COPY --from=builder /app/main .

EXPOSE 8080

CMD ["./main"]
