import { create } from 'zustand';
import type { GameState } from '@/types/type';

export const useGameStore = create<GameState>((set) => ({
   myPlayerId: '',
   myName: '',
   roomCode: '',
   isHost: false,
   hasPassword: false,
   players: [],
   currentQuestion: null,
   gameStatus: 'LOBBY',
   winnerInfo: null,
   error: null,
   readyIds: [],
   iAmReady: false,
   answerInput: '',
   timeRemaining: 30,
   wrongAnswers: [],
   phoneticsData: null,
   lastTotalRounds: 0,
   setMyInfo: (myPlayerId, myName) => set({ myPlayerId, myName }),
   setRoomCode: (roomCode) => set({ roomCode }),
   setIsHost: (isHost) => set({ isHost }),
   setHasPassword: (hasPassword) => set({ hasPassword }),
   setPlayers: (players) => set({ players }),
   setCurrentQuestion: (currentQuestion) => set({ currentQuestion, winnerInfo: null }),
   setGameStatus: (gameStatus) => set({ gameStatus }),
   setWinnerInfo: (winnerInfo) => set({ winnerInfo }),
   setError: (error) => set({ error }),
   setReadyUpdate: (readyIds) => set({ readyIds }),
   setIAmReady: (iAmReady) => set({ iAmReady }),
   setAnswerInput: (answerInput) => set({ answerInput }),
   setTimeRemaining: (timeRemaining) => set({ timeRemaining }),
   setWrongAnswers: (wrongAnswers) => set({ wrongAnswers }),
   addWrongAnswer: (answer) => set((state) => ({ wrongAnswers: [...state.wrongAnswers, answer] })),
   setPhoneticsData: (phoneticsData) => set({ phoneticsData }),
   setLastTotalRounds: (lastTotalRounds) => set({ lastTotalRounds }),
   resetRoom: () =>
      set({
         players: [],
         currentQuestion: null,
         gameStatus: 'LOBBY',
         winnerInfo: null,
         isHost: false,
         hasPassword: false,
         error: null,
         readyIds: [],
         iAmReady: false,
         answerInput: '',
         timeRemaining: 30,
         wrongAnswers: [],
         phoneticsData: null,
         lastTotalRounds: 0,
      }),
}));
